honeycomb/honeycomb.go

We decided to move away from calling MessageEvents annotations and instead call them SpanEvents to be more inline with the OpenTelemetry Spec
Also moves the Timestamp to the base event so as not to get that duplicate timestamp we were seeing before.

rename Annotation to SpanEvent

---

honeycomb/honeycomb.go
honeycomb/honeycomb_test.go

In order to hide these SpanEvents by default in the UI, I'm adding the `meta.span_event` field

add spanEvent boolean field

---

README.md
example/README.md
example/basic_example/main.go
example/client/client.go
example/server/server.go
honeycomb/honeycomb.go
honeycomb/honeycomb_test.go

Moves the default sampler config to the exporter
Adds a pointer to the honeycomb docs to the main readme and updates the examples readme

move the default sampler to the exporter

---

README.md
example/basic_example/main.go
example/client/client.go
example/server/server.go
honeycomb/honeycomb.go
honeycomb/honeycomb_test.go

**NOTE: Breaking change!**
In order to allow an option debug mode, and to make further additions to the honeycomb config easier in the future, this changes the `NewExporter` call to take a `Config` type, rather than the ApiKey and Dataset directly.
Debug mode is then enabled directly in the config, and that is passed through to the libhoney config.
https://github.com/honeycombio/opentelemetry-exporter-go/issues/15

Add optional debug mode

---

honeycomb/honeycomb.go
honeycomb/honeycomb_test.go

As per [the slack conversation](https://houndsh.slack.com/archives/CM4MFEM3K/p1568659034011800?thread_ts=1568659034.011800), let's use the existing meta.span_type field that we use in other beelines, setting the value to span_event.
We will look at this tag on the Honeycomb side and handle these spans accordingly

Change spanEvent tag

---

honeycomb/honeycomb.go

This exposes the APIHost config field so I can run this locally.
Libhoney will default to api.honeycomb.io if this is not explicitly set, so no need to provide that default here.

expose APIHost so i can point this at my local api instance

---

honeycomb/honeycomb_test.go

Removes flaky test. 
This test has flaked a few times, let's remove it.
Duration should be more than 0, but we don't really care if it's less than 1. It's more likely to fail on circleci than locally.

Fix flakey test

---

go.mod
go.sum
honeycomb/honeycomb.go
honeycomb/honeycomb_test.go

Upgrades to the latest OTel
This pulls out our custom parsing of `traceID` and uses `TraceIdString` and `SpanIDString` instead. Still uses UUID to parse it, though.

update otel, and switch to using TraceIdString and SpanIDString

---

example/basic_example/main.go
example/client/client.go
example/server/server.go
honeycomb/honeycomb.go
honeycomb/honeycomb_test.go

This adds error handling in 2 ways.
1. It returns an error if we're unable to initialize libhoney when trying to register the exporter
2. It adds an OnError handler to the config and exporter that defaults to logging when we are unable to send an event to honeycomb.
Resolves https://github.com/honeycombio/opentelemetry-exporter-go/issues/29

add error handling

---

honeycomb/honeycomb.go
honeycomb/honeycomb_test.go

We no longer use duration_ms = 0 for visualization in the UI - this removes it from the SpanEvent payload

remove duration milli from span event payload

---

honeycomb/honeycomb.go
honeycomb/honeycomb_test.go

This is the main Link struct.
The Trace is the current trace (so we know where to visualize it)
The ParentID is the span that is currently active
The other 4 methods are related to the link itself - the trace and span ids from the span context, the refType - which is currently unsupported. (For now, I'm using Child_Of like the Jaeger exporter does, but have put in a todo to update that when there are different ref types)
`SpanType` will be used in the UI to pull these out into the trace sidebar.
```
type Link struct {
TraceID     string      `json:"trace.trace_id"`
ParentID    string      `json:"trace.parent_id,omitempty"`
LinkTraceID string      `json:"trace.link.trace_id"`
LinkSpanID  string      `json:"trace.link.span_id"`
SpanType    string      `json:"meta.span_type"`
RefType …
```

adds support for links

---

.circleci/config.yml

Previously, go modules wasn't turned on, so circleci was pulling the latest otel - which inevitably broke the build if I hadn't updated in ... a day or two.

turn on go modules for circle-ci config

---

example/client/client.go
go.mod
go.sum
honeycomb/honeycomb.go

Updates distributedcontext and keyvalue syntax. (PRs that forced us to change below)
https://github.com/open-telemetry/opentelemetry-go/pull/256
https://github.com/open-telemetry/opentelemetry-go/pull/252

Update OpenTelemetry to 20191031 version

---

example/client/client.go
example/server/server.go
honeycomb/honeycomb.go
honeycomb/honeycomb_test.go

We no longer need SimpleSpanProcessor as the boilerplate is a lot more efficient now out of the box with otel.

NewProvider is the new standard init method.

---

go.mod
go.sum
honeycomb/honeycomb.go
honeycomb/translator.go

The OpenTelemetry collector exports trace data to exporters as a [TraceData](https://godoc.org/github.com/open-telemetry/opentelemetry-collector/consumer/consumerdata#TraceData) struct. In order to reuse the `ExportSpan` function in the SDK exporter, we'll need to convert these to [SpanData](https://godoc.org/go.opentelemetry.io/otel/sdk/export/trace#SpanData) structs. This PR adds a translators file to the opentelemetry-exporter-go package with a single exported function, `OCProtoSpanToOtelSpanData` that the collector will use to do the conversion.
Also making the UserAgent string used by `libhoney-go` configurable so that we can distinguish OpenTelemetry exporter events from OpenTelemetry collector events. 
See [relevant code in collector …

Adding translator to create OTel SDK Spans from OC Proto Spans

---

README.md
example/client/client.go
example/server/server.go
go.mod
honeycomb/honeycomb.go
honeycomb/honeycomb_test.go
honeycomb/translator.go

Migrate optional configuration fields to functional options, making it more clear what's required to create a functional `honeycomb.Exporter`.
Accommodate both static and dynamic global event fields—analogous to `libhoney.Client`'s `AddField` and `AddDynamicField` methods and the `libhoney.AddField` and `libhoney.AddDynamicField` functions—with the following new functional options accepted by the `NewExporter` function:
- `WithField`  
(A single field with a static value.)
- `WithFields`  
(A set of fields with static values.)
- `WithDynamicField`  
(A single field with a dynamic value.)
- `WithDynamicFields`  
(A set of fields with dynamic values.)
Since this module remains well ahead of a major version release, **this patch includes incompatible changes**, removing several exported …

Configure exporter mostly with functional options

---

honeycomb/translator.go

This `honeycomb.TimestampToTime` function is only used within the "honeycomb" package, so don't export it any longer, reducing the surface area of the package. Rename it to `timestampToTime` to protect it from outsiders.

Don't export the honeycomb.TimestampToTime function

---

go.mod
honeycomb/translator.go
honeycomb/translator_test.go

Adds support for setting:
* HasRemoteParent field from the SameProcessAsParentSpan OC field (inverted)
* Status from the Status.Code OC field
* MessageEvents from OC Annotations
Adds a test case for the translator.

Add support for HasRemoteParent, Status and MessageEvents to OC proto translator

---

honeycomb/honeycomb.go
honeycomb/honeycomb_test.go
honeycomb/translator.go

OpenTelemetry providers have [an optional "resource"](https://pkg.go.dev/go.opentelemetry.io/otel@v0.4.2/sdk/trace?tab=doc#Config) defined, with an accompanying set of indelible attributes meant for inclusion in all published spans. These are analogous to _libhoney_'s [client-](https://godoc.org/github.com/honeycombio/libhoney-go#Client.Add) and [builder-level fields](https://godoc.org/github.com/honeycombio/libhoney-go#Builder.Add), but these resource attributes should override any same-keyed attributes set on a particular span.
Export these resources when present, with their attributes overlaying any competing attributes in each span.

Accommodate OpenTelemetry provider resource in Honeycomb events

---

honeycomb/honeycomb.go
honeycomb/honeycomb_test.go

Rather than overlaying attributes defined by an OpenTelemetry ["resource"](https://pkg.go.dev/go.opentelemetry.io/otel@v0.4.2/sdk/trace?tab=doc#Config) atop span- and message-level attributes, instead treat the resource attributes as an underlay, establishing default values that are overridden by any spans or messages defining attributes with the same
key.
Note that for Honeycomb, static and dynamic fields defined on the exporter by way of the [`WithField*`](https://godoc.org/github.com/honeycombio/opentelemetry-exporter-go/honeycomb#WithField) and [`WithDynamicField*`](https://godoc.org/github.com/honeycombio/opentelemetry-exporter-go/honeycomb#WithDynamicField) functions sit lower than resource attributes. Message and span attributes trump resource attributes, and resource attributes …

Treat OpenTelemetry provider resource attributes as underlays in Honeycomb events

---

honeycomb/honeycomb.go
honeycomb/honeycomb_test.go

In order to allow easier querying for span events that are attached to spans with particular "name" field values, transcribe the parent span's "name" field value to each child message event's "trace.parent_name" field.
I chose the proposed new event field name to mimic the existing "trace.parent_id" field.

Record parent span name attribute on attached span events to ease querying

---

go.mod
go.sum
honeycomb/honeycomb.go
honeycomb/honeycomb_test.go

We lost the `core.SpanContext` type's `SpanIDString` and `TraceIDString` methods, in favor of implementing the `Stringer` interface on the `core.SpanID` and `core.TraceID` types. Use the new `String` methods on those types instead.
Fixes #74.

Use the newly implemented Stringer interface on the core.(Span|Trace)ID types

---

go.sum
honeycomb/honeycomb.go
honeycomb/honeycomb_test.go

Parsing all incoming trace ids as UUIDs can introduce formatting incompatibilities between Honeycomb and other tracing tools. Specifically, Jaeger supports either 64-bit or 128-bit trace ids. The OpenTelemetry Collector will left-pad 64-bit ids with 0s, which were then being converted into UUIDs by the Honeycomb exporter, leading to strings like 00000000-0000-0000-cbe4-decd12429177.
This change simply accepts either 64-bit or 128-bit ids and doesn't parse them into UUIDs. The above example would be passed through as cbe4decd12429177.

Don't parse incoming trace ids as UUIDs.

---

CHANGELOG.md
honeycomb/honeycomb.go
honeycomb/honeycomb_test.go

using a `libhoney.Client` should isolate the exporter a bit more from the rest of a user's code (if they happen to be using another `libhoney.Client`, or the package api.)  We can drop the `Builder` and use the client instead.
`libhoney.ClientConfig` doesn't support an `Output` field, so we need to switch from `libhoney.Output` to `transmission.Sender`.  This is a breaking change:  here we drop `withHoneycombOutput` and replace it with `withHoneycombSender`.
There is one remaining thing to call out about `libhoney.Client` isolation - `libhoney.UserAgentAddition`.
1. By offering a way for user code to specify a `transmission.Sender`, we lose the ability to specify the user agent at all in those cases.  Not sure if there's code in the wild that does this.  The tests are the only place …

use a libhoney.Client; switch from libhoney.Output to transmission.Sender
